Add missing functionality to context
Keats/tera2 pull request #29
Opened 2024-01-12 14:39 UTC by GandelXIV

Quick commit porting the following functions to tera2
- https://docs.rs/tera/latest/tera/struct.Context.html#method.get
- https://docs.rs/tera/latest/tera/struct.Context.html#method.into_json
- https://docs.rs/tera/latest/tera/struct.Context.html#method.contains_key

2024-01-13 17:04 UTC, Keats requested changes

2024-01-13 17:04 UTC, Keats commented on src/context.rs
> +    pub fn to_json(&self) -> Result<String, serde_json::Error> {
That shouldn't be added back

2024-01-14 16:09 UTC, GandelXIV commented on src/context.rs
> +    pub fn to_json(&self) -> Result<String, serde_json::Error> {
Alright

2024-01-15 08:52 UTC, Keats approved these changes

2024-01-15 08:52 UTC, merged